plugins {
    id 'java'
    id 'com.gradleup.shadow'
}

dependencies {
    implementation project(':common')
    compileOnly 'cn.nukkit:nukkit:1.0-SNAPSHOT'
}

shadowJar {
    archiveClassifier.set('')
    archiveBaseName.set('AxiomAntiVPN-NukkitX')
}

build.dependsOn shadowJar

processResources {
    filesMatching('plugin.yml') { expand(version: project.version) }
}
