plugins {
    id 'java'
    id 'com.gradleup.shadow' version '9.6.1' apply false
}

allprojects {
    group = 'com.axiom.antivpn'
    version = providers.gradleProperty('buildVersion')
            .orElse(providers.environmentVariable('BUILD_VERSION'))
            .orElse('1.0.2')
            .get()
}

subprojects {
    apply plugin: 'java'

    java {
        toolchain {
            languageVersion = JavaLanguageVersion.of(21)
        }
    }

    compileJava {
        options.encoding = 'UTF-8'
        options.release = 21
        options.compilerArgs += ['-parameters']
    }

    repositories {
        mavenCentral()
        maven { url = 'https://hub.spigotmc.org/nexus/content/repositories/snapshots/' }
        maven { url = 'https://oss.sonatype.org/content/repositories/snapshots/' }
        maven { url = 'https://central.sonatype.com/repository/maven-snapshots/' }
        maven { url = 'https://repo.papermc.io/repository/maven-public/' }
        maven { url = 'https://repo.opencollab.dev/main/' }
        maven { url = 'https://repo.helpch.at/releases/' }
        maven { url = 'https://repo.nukkitx.com/maven-releases/' }
    }

    dependencies {
        compileOnly 'org.jetbrains:annotations:26.1.0'
    }
}
