plugins {
    id 'java'
    id 'com.gradleup.shadow'
}

dependencies {
    implementation project(':common')
    compileOnly 'io.papermc.paper:paper-api:1.21.11-R0.1-SNAPSHOT'
    implementation 'io.github.revxrsal:lamp.common:4.0.0-rc.17'
    implementation 'io.github.revxrsal:lamp.bukkit:4.0.0-rc.17'
}

shadowJar {
    archiveClassifier.set('')
    archiveBaseName.set('AxiomAntiVPN-Bukkit')

    relocate 'com.github.benmanes.caffeine', 'com.axiom.antivpn.libs.caffeine'
    relocate 'com.google.gson', 'com.axiom.antivpn.libs.gson'
    relocate 'revxrsal.commands', 'com.axiom.antivpn.libs.lamp'

    minimize {
        exclude dependency('com.github.ben-manes.caffeine:.*')
        exclude dependency('io.github.revxrsal:.*')
        exclude dependency('org.xerial:sqlite-jdbc:.*')
    }
}

build.dependsOn shadowJar
