plugins {
    id 'java'
    id 'com.gradleup.shadow'
}

dependencies {
    implementation project(':bukkit')
    compileOnly 'dev.folia:folia-api:1.21.11-R0.1-SNAPSHOT'
}

shadowJar {
    archiveClassifier.set('')
    archiveBaseName.set('AxiomAntiVPN-Folia')
}

build.dependsOn shadowJar

processResources {
    filesMatching('plugin.yml') { expand(version: project.version) }
}
